### ISSUE TITLE
[Chatbot] LLM Chatbot Question Answer Endpoint

### ISSUE THREAD

**Issue by tuantran0910** [TinhHoaSolutions-EzHR/chatbot#16]
**Task**: Create an endpoint for LLM Chatbot Interaction.
- You need to use **LlamaIndex** as LLM framework.
- View the instruction for developing backend in the file `backend/README.md`.

**Output**: There is an endpoint so that we can make request to this and receive the LLM's response.

> **Note**: Please provide a clean code. Don't hard code, just simply put it as constant in file `backend/settings.py`. If you don't know whether your code is clean or not, ask GPT to refractor your code. 

> **Important**: Always make sure that code can run without any errors.

**Comment by lelouvincx** [comment]
Changed to #51
