### ISSUE TITLE
[Chatbot] Review current frontend progress

### ISSUE THREAD

**Issue by lelouvincx** [TinhHoaSolutions-EzHR/chatbot#24]

**Comment by lekiet1214** [comment]
@greyyT can you update the project structure here for documentation? or update the [README](https://github.com/TinhHoaSolutions-EzHR/chatbot/blob/c8bcd471def338890a26b065799bbed02530f82b/chatbot-core/frontend/README.md)

**Comment by lelouvincx** [comment]
Closed, duplicated with #64
