### ISSUE TITLE
Docker Compose for Frontend Development

### ISSUE THREAD

**Issue by greyyT** [TinhHoaSolutions-EzHR/chatbot#25]
**Is your feature request related to a problem? Please describe.**

I am facing inefficiencies in my development workflow because the frontend can only run through Docker Compose, requiring a full build each time, which slows down my progress.

**Describe the solution you'd like**

I propose a Docker Compose file that exposes only the backend API, allowing the frontend to call it directly and enabling hot reloading with Next.js.

**Describe alternatives you've considered**

I considered running the backend and frontend separately outside of Docker, but this complicates our setup and consistency.

**Additional context**

This change would significantly improve development speed. Any guidance on implementation would be appreciated.

**Comment by lelouvincx** [comment]
Ok I will handle it for you <3 <3 <3

**Comment by lelouvincx** [comment]
Duplicated with #35, closing.
